on: [push, pull_request]
name: "CI"

defaults:
  run:
    shell: bash

jobs:
  build-toolchain:
    strategy:
      fail-fast: false
      matrix:
        toolchain: ["stable", "1.56", "beta", "nightly"]
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all-features

  build-os:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all-features

  build-features:
    strategy:
      fail-fast: false
      matrix:
        features:
          - "--no-default-features"
          - '--features ""'
    runs-on: ubuntu-latest
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build ${{ matrix.features }}

  lint:
    runs-on: ubuntu-26.04
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - uses: j178/prek-action@v1

  test:
    runs-on: ubuntu-26.04
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features

  semver:
    runs-on: ubuntu-26.04
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v7
      - name: Check SemVer
        uses: obi1kenobi/cargo-semver-checks-action@v2
